python3 kmeans_clustering_test.py >> out.txt
python3 kmeans_clustering_test.py >> out.txt
python3 kmeans_clustering_test.py >> out.txt
python3 kmeans_clustering_test.py >> out.txt
python3 kmeans_clustering_test.py >> out.txt
python3 kmeans_clustering_test.py >> out.txt
python3 kmeans_clustering_test.py >> out.txt
python3 kmeans_clustering_test.py >> out.txt
python3 kmeans_clustering_test.py >> out.txt
python3 kmeans_clustering_test.py >> out.txt